create database customerchurnn;
USE CUSTOMERCHURNN;
CREATE TABLE CSTRCHURN(
CUSTOMER_ID INT NOT NULL,
GENDER VARCHAR(10),
SENIOR_CITIZEN INT,
PARTNER VARCHAR(10),
DEPENDENCE VARCHAR(10),
TENURE INT,
PHONE_SERVICE VARCHAR(30),
MULTIPLELINES VARCHAR(30),
INTERNETSERVICE VARCHAR(30),
ONLINESECURITY VARCHAR(30),
ONLINEBACKUP VARCHAR(30),
DEVICEPROTECTION VARCHAR(30),
TECHSUPPORT VARCHAR(30),
STREAMING_TVS VARCHAR(30),
STREAMING_MOVIES VARCHAR(30),
CONTRACT VARCHAR(30),
PAPERLES_BILLING VARCHAR(30),
PAYMENT_METHOD VARCHAR(30),
MONTHLY_CHARGE DECIMAL(10,2),
TOTAL_CHARGE DECIMAL(10,2),
CHURN VARCHAR(10)
);
SHOW TABLES;
DESCRIBE CSTRCHURN;`wa_fn-usec_-telco-customer-churn``wa_fn-usec_-telco-customer-churn`
SELECT COUNT(*) FROM CSTRCHURN;
SHOW TABLES;
select count(*) FROM `wa_fn-usec_-telco-customer-churn`;
drop table cstmrchurn;
DROP TABLE cstrchurn;
RENAME TABLE `wa_fnusec_-telco-customer-churn`
TO telecom_churn;
SELECT COUNT(*) FROM `wa_fn-usec_-telco-customer-churn`;
RENAME TABLE `wa_fn-usec_-telco-customer-churn` TO TELECOM_CHURN;
SELECT COUNT(*) FROM TELECOM_CHURN;
describe TELECOM_CHURN;

create database churn;
use churn;
show tables;
select count(*) from cleaned_data;
describe cleaned_data;

-- 1.TOTAL CHURN:-
SELECT CHURN, COUNT(*) as count,
count(*)*100/7032 as percentage
FROM CLEANED_DATA
group by churn;
-- NEARLY 26% OF CUSTOMERS HAVE CHURNED, INDICATING A RETENSION ISSUE 




-- 2.CONTRACT ANALYSIS:-
SELECT CONTRACT, COUNT(*) AS TOTAL_CUSTOMER,
SUM(CASE WHEN CHURN = 'YES' THEN 1 ELSE 0 END) AS CHURNED_CON
FROM CLEANED_DATA
GROUP BY CONTRACT;
-- CUSTOMER ON MONTH-TO-MONTH CONTRTACT SHOW SIGNIFICANLY HIGHER CHURN THAN LONGER CONTRACT.
-- THIS SHOWS LACK OF COMITMENT LEADS TO HIGHER CHURN



-- 3.TENURE ANALYSIS:-
SELECT 
CASE
WHEN TENURE < 12 THEN '0-1'
WHEN TENURE < 24 THEN '1-2'
ELSE '2+'
END AS TENURE_GROUP,
COUNT(*) AS TOTAL,
SUM(CASE WHEN CHURN = 'YES' THEN 1 ELSE 0 END) AS TOTAL_CHURN
FROM CLEANED_DATA
GROUP BY TENURE_GROUP
ORDER BY TENURE_GROUP;
-- CUSTOMER WITH LOWER TENURE HAS HIGHEST CHURN RATE
-- EARLY STAGE CUSTOMER EXPERIENCE IS CRITICAL FOR RETENTION



-- 4.PAYMENT METHOD ANALYSIS:-
SELECT PAYMENTMETHOD, COUNT(*) AS TOTAL,
SUM(CASE WHEN CHURN = 'YES' THEN 1 ELSE 0 END) AS TOTAL_CHURN
FROM CLEANED_DATA
GROUP BY PAYMENTMETHOD;
-- Customers using electronic check show higher churn



-- 5.CHARGES ANALYSIS
SELECT CHURN, AVG(MONTHLYCHARGES)
FROM CLEANED_DATA
GROUP BY CHURN;
-- Customers with higher monthly charges tend to churn more



-- 6.INTERNET SERVICE ANALYSIS
SELECT InternetService,COUNT(*) AS TOTAL_INTSERV,
SUM(CASE WHEN CHURN ="YES" THEN 1 ELSE 0 END) AS TOTAL_CHURN
FROM CLEANED_DATA
GROUP BY InternetService;
-- Fiber optic users often show higher churn compared to DSL









